name: Run Unit Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PERSIST_SANDBOX : "false"

jobs:
  test-on-macos:
    name: Test on macOS
    runs-on: macos-12
    env:
      INSTALL_DOCKER: "1" # Set to '0' to skip Docker installation
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: OpenDevin/OpenDevin

      - name: Install poetry via pipx
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Python dependencies using Poetry
        run: poetry install

      - name: Install & Start Docker
        if: env.INSTALL_DOCKER == '1'
        run: |
          # Uninstall colima to upgrade to the latest version
          if brew list colima &>/dev/null; then
              brew uninstall colima
              # unlinking colima dependency: go
              brew uninstall go@1.21
          fi
          rm -rf ~/.colima ~/.lima
          brew install --HEAD colima
          brew services start colima
          brew install docker
          colima start  --network-address --arch x86_64 --cpu=1 --memory=1

          # For testcontainers to find the Colima socket
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

      - name: Build Environment
        run: make build

      - name: Run Tests
        run: poetry run pytest --forked --cov=agenthub --cov=opendevin --cov-report=xml ./tests/unit -k "not test_sandbox"

